### ISSUE TITLE
Usage with Sanity UI & Icons?

### ISSUE THREAD

**Issue by dorelljames** [rexxars/sanipack#2]
I'm not sure if it's appropriate to file this as an issue so my apologies in advance if it's so. I've never been good with tooling, to begin with, so yeah, please bear with me.

So, I created a Sanity plugin that imports [@sanity/ui](https://www.npmjs.com/package/@sanity/ui) and [@sanity/icons](https://www.npmjs.com/package/@sanity/icons). [It comes by default in Sanity Studio](https://www.sanity.io/ui/docs/guide/sanity-studio) and it was working great before when it was in the `plugins` directory.

The problem now when I packed things up using this tool, it can't seem to find those mentioned imports above. I've added them as `peer dependencies` to no avail. 

So what I did is to install those packages and now their added as `dependencies` in my Sanity plugin. Is this fine or what could I be missing here? Thanks a lot. 🙏

**Comment by rexxars** [comment]
Hi Dorell! Sorry, didn't see this issue until now.

You'll want to declare `@sanity/ui` and `@sanity/icons` (if you are using them) as regular dependencies in your plugin. That ensures that different plugins can use different version fo those packages without causing issues. npm/yarn will try to ensure that there are as few copies as possible in the dependency tree at the same time, based on the dependency version range in the different consumer package.json files.

Hope that helps!
