### ISSUE TITLE
sanity.json parts path check fails if path includes period (.)

### ISSUE THREAD

**Issue by runeb** [rexxars/sanipack#4]
```json
{
  "paths": {
    "source": "src",
    "compiled": "dist"
  },
  "parts": [
    {
      "implements": "part:@sanity/base/schema-type",
      "path": "schema/my.asset"
    }
  ]
}
```
Fails with ```
[error] Invalid sanity.json: Part path references file that does not exist in source directory (/Users/user/src/sanity-plugin-project/src) (parts[0])```

even though there is a file `src/schema/my.asset.js`. Removing the dot in both the file name and path value fixes the issue

**Comment by rexxars** [comment]
Fixed in v1.0.10 - thanks for reporting!
